### ISSUE TITLE
The replace response feature does not work

### ISSUE THREAD

**Issue by theblackturtle** [synfron/ReshaperForBurp#1]
Hi, 

It seems the replacement on the response (status code, body,..) does not work. It working when replacing on the request. Can you check it again?

Thanks.

**Comment by ddwightx** [comment]
Hello, thanks for contacting. From what I understand, you want to change a part of the response that comes back from the server? Do you have the When > Event Direction set to Response in your rule? This makes sure that you are editing the response after it comes back from the server.

**Comment by ddwightx** [comment]
See [Change a value in a returned response](https://synfron.github.io/ReshaperForBurp/Examples.html#tip3) as an example. Note step #3 and #4.

**Comment by theblackturtle** [comment]
Hi @ddwightx, It's working. Thanks for your support and created this awesome extension.

**Comment by ddwightx** [comment]
That's great news. You're welcome, glad you like it!
