### ISSUE TITLE
Feature request: new "Thens" to raise a burp finding  

### ISSUE THREAD

**Issue by fyoorer** [synfron/ReshaperForBurp#13]
It would be great if there is a Thens function that can raise Burp issue 

Something like
 - Run process
 Initial Text
 Description
 Severity
 Level - firm, certain etc.

**Comment by ddwightx** [comment]
Thanks for the suggestion. I'll look into this.

**Comment by ddwightx** [comment]
It looks like this functionality requires Burp Suite Pro so I will be unable to pursue this feature since I will not be able to test it or maintain it. Sorry about that.
