### ISSUE TITLE
Send Request not accepting Port specified using a variable

### ISSUE THREAD

**Issue by migueldilaj** [synfron/ReshaperForBurp#20]
Hi!
Tried to create a Send Request on which the port was specified using a global variable, and it didn't accept it with the error message "Post must be an integer".
The variable contains an integer.
The online docs mention that Port "Supports variable tags".
Protocol and Address accepted variables without a problem.

**Comment by ddwightx** [comment]
There appears to be a bug in the validation. I will get that fixed.

As a workaround for now, put zero `0` right before the variable tag like `0{{g:MyVar}}` and that should get it past the validation error.

**Comment by migueldilaj** [comment]
Perfect. That workaround did the trick in the mean time. Thanks!

**Comment by ddwightx** [comment]
@migueldilaj v1.8.2 has been released to the  BApp Store. This issue should be fixed now.
