### ISSUE TITLE
Bold or highlight rule name if the rule is enabling

### ISSUE THREAD

**Issue by theblackturtle** [synfron/ReshaperForBurp#4]
Hi, 
When using many rules, there is no way to know which rule is enabling. Can you add the bold or the highlight for the rule enabling? 
Thanks.

**Comment by ddwightx** [comment]
That does seem like a worthy thing to look into. Thanks for the suggestion.

**Comment by ddwightx** [comment]
This has been added in commit 6ce8cf7e7df20b07e2ef6524ca552776805a94ec and has been submitted to the BApp Store for review.

**Comment by ddwightx** [comment]
This update should now be live in the BApp Store
