### ISSUE TITLE
Feature Request: Remember Last Folder

### ISSUE THREAD

**Issue by rob-ip** [synfron/ReshaperForBurp#45]
Great extension!

Would it be possible for functionality to be implemented for `Import Data` and `Export Data` to remember the last folder used?

**Comment by ddwightx** [comment]
Feature targeted for next release, tracked in https://github.com/synfron/ReshaperForBurp/issues/50.

**Comment by ddwightx** [comment]
@rob-ip If you want, feel free to test if this pre-release addresses your request. https://github.com/synfron/ReshaperForBurp/releases/tag/v2.3.0-pre

**Comment by rob-ip** [comment]
Thank you! I'll take a look.
