### ISSUE TITLE
WebSockets - Exception on Run Process

### ISSUE THREAD

**Issue by rob-ip** [synfron/ReshaperForBurp#47]
Hi

I'm trying to automatically decode a binary protocol over WS using Reshaper - MacOS 13.4 (22F66) / Burp Suite Pro v2023.10.1.2.

My setup in `Thens` under `WebSocket Rules`:

```
Set Variable ->
    Use Message Value = Checked
    Source Message Value = WebSocket Message
    Source Value Type = Text

    Destination Variable Source = Session
    Destination Variable Name = message
    Destination Value Type = Text

Run Process ->
    Command = python3 /path/to/decoder
    StdIn = {{sn:message}}
```

However,  it gets the following exception:

`java.io.IOException: Broken pipe\nsynfron.reshaper.burp.core.exceptions.WrappedException: java.io.IOException: Broken pipe\n\tat synfron.reshaper.burp.core.rules.thens.ThenRunProcess.perform(ThenRunProcess.java:121)\n\tat synfron.reshaper.burp.core.rules.thens.IThenGroup.perform(IThenGroup.java:20)\n\tat synfron.reshaper.burp.core.rules.RulesEngine.run(RulesEngine.java:47)\n\tat synfron.reshaper.burp.core.rules.RulesEngine.run(RulesEngine.java:21)\n\tat synfron.reshaper.burp.core.WebSocketConnector$WebSocketMessageConnector.processEvent(WebSocketConnector.java:117)\n\tat synfron.reshaper.burp.core.WebSocketConnector$WebSocketMessageConnector.handleBinaryMessageReceived(WebSocketConnector.java:91)\n\tat burp.Zhxr.ZO(Unknown Source)\n\tat burp.Zi_m.ZJ(Unknown Source)\n\tat burp.Zit9.ZD(Unknown Source)\n\tat net.portswigger.Zfk.run(Unknown Source)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1589)\nCaused by: java.io.IOException: Broken pipe\n\tat java.base/java.io.FileOutputStream.writeBytes(Native Method)\n\tat java.base/java.io.FileOutputStream.write(FileOutputStream.java:372)\n\tat java.base/java.io.BufferedOutputStream.implWrite(BufferedOutputStream.java:216)\n\tat java.base/java.io.BufferedOutputStream.write(BufferedOutputStream.java:205)\n\tat java.base/java.io.FilterOutputStream.write(FilterOutputStream.java:108)\n\tat org.apache.commons.io.IOUtils.write(IOUtils.java:3251)\n\tat synfron.reshaper.burp.core.rules.thens.ThenRunProcess.perform(ThenRunProcess.java:74)\n\t... 14 more\n",`

If I do 

```
Save File ->
    File Path = /my/file/path
    Text = {{sn:message}}
    Encoding = Default
    File Exists Action = Overwrite
```

If I then run `python3 /path/to/decoder < /my/file/path` works.

Should my approach work in Reshaper?

Thanks

**Comment by ddwightx** [comment]
Unfortunately, I'm unable to reproduce the issue. I've made my own python script to test this:

pytest file
```
import sys

for line in sys.stdin:
    print ("Decoding: " + line, end="")
```

For the Thens, I tested with:
Set Variable
  Source Message Value: `WebSocket Message`
  Destination Variable Source: `Session`
  Destination Variable Name: `message`
Run Process
  Command: `python3 /path/to/pytest
  Stdin: `{{sn:message}}`
  Wait for Completion: `Checked`
  Capture Output: `Checked`
  Capture Variable Source: `Global`
  Capture Variable Name: `decoded_message`

I then send a WebSocket message `Hello World` and verified that the variable `decoded_message` contains the text `Decoding: Hello World`
---
Can you see if the above works on your machine?
Is it possible your `decoder` program is terminating while the stdin is being fed to it?

**Comment by ddwightx** [comment]
Will make a change that should generally improve Run Process on UNIX based systems. Fix targeted for next release, tracked in https://github.com/synfron/ReshaperForBurp/issues/50.

**Comment by ddwightx** [comment]
@rob-ip If you want, feel free to test if this pre-release addresses your issue. https://github.com/synfron/ReshaperForBurp/releases/tag/v2.3.0-pre
