### ISSUE TITLE
Usage with Hackvertor?

### ISSUE THREAD

**Issue by ldionmarcil** [synfron/ReshaperForBurp#57]
Hi, I noticed that I cannot use hackvertor tags with reshaper, which is unfortunate. Is this something that could easily be done? I tried changing the extension load order, but that didn't change much.
My use case is that I am storing something in a variable, and I want to reference it later but urlencoded. I did not find a way to do that with Reshaper proper. Unfortunately if I do <@urlencode>{{g:myvar}}<@/urlencode>, Hackvertor does not pick it up.

Thanks

**Comment by ldionmarcil** [comment]
I figured it out, it's not an issue with Reshaper. I needed to enable "Allow tags in Proxy" in the Hackvertor config. 
<img width="295" alt="image" src="https://github.com/synfron/ReshaperForBurp/assets/1320868/c08f51d8-5608-412d-b1fb-e3325b373b1e">

**Comment by ddwightx** [comment]
@ldionmarcil Also, in case you couldn't rely on Hackvector for whatever reason, you could use a Then Run Script where you can use JavaScript `encodeURI` or `encodeURIComponent` functions to encode text.
