### ISSUE TITLE
Reshaper does not work when "From tool" is anything other than Proxy

### ISSUE THREAD

**Issue by fyoorer** [synfron/ReshaperForBurp#60]
When the "From Tool" condition is used in a When with any other tool other than Proxy (e.g Repeater, Intruder), Reshaper does not apply the rule.

I created a simple rule like this:
![image](https://github.com/synfron/ReshaperForBurp/assets/65155/a2d5a4a9-b96e-4447-acaf-6b84c030fd27)

Whats expected:
Log entry should be created for each request sent through Repeater.

Actual behavior: 
Log was not created after sending requests from Repeater.

Burp version 2024.2.1.5 stable
Reshaper version: 2.3.3

**Comment by ddwightx** [comment]
If you remove the From Tool constraint, do you see the log of the request? If not, that means you probably do not have those tools selected in the Settings tab of Reshaper.

**Comment by fyoorer** [comment]
oh damn 🤦 
yeah, I didnt have those tools selected in the settings.
