### ISSUE TITLE
How to import javascript library using Run Script

### ISSUE THREAD

**Issue by darkcyber** [synfron/ReshaperForBurp#67]
Hi,

I'm wondering if it is possible to call javascript library using Run Script function?

in this case, I would like to call Crypto-JS https://www.npmjs.com/package/crypto-js and use it.

Something like below

```
var CryptoJS = require("crypto-js");

// Encrypt
var ciphertext = CryptoJS.AES.encrypt('my message', 'secret key 123').toString();

// Decrypt
var bytes  = CryptoJS.AES.decrypt(ciphertext, 'secret key 123');
var originalText = bytes.toString(CryptoJS.enc.Utf8);

console.log(originalText); // 'my message'
```

I think, I can achieve my goal using Run Process. But I would like to know if it is possible using Run Script function

Thanks

**Comment by ddwightx** [comment]
You can use the technique below.

Copy the source code of the library to a global variable. If you don't have another source to get it from, you can copy it from https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.2.0/crypto-js.min.js.

![image](https://github.com/synfron/ReshaperForBurp/assets/48854453/fa94caa9-cdc2-4daf-b7e2-087e8f70b3ac)

Then in the Run Script, you can use it like this:

```
eval(Reshaper.variables.getGlobalVariable("cryptojs")); // Important part here. Change the variable name as needed.
var value = CryptoJS.enc.Utf8.parse("Hello");
var encoded = CryptoJS.enc.Base64.stringify(value);
console.log(JSON.stringify(encoded));
```
