### ISSUE TITLE
Then > Parse HTTP Message Error

### ISSUE THREAD

**Issue by rhamaa** [synfron/ReshaperForBurp#71]
I tried all of the Then Parse HTTP Message > Message Value, then i will got this kind of error

![image](https://github.com/user-attachments/assets/08461f60-ea5b-4893-9f20-9104cd835200)

Burp Profesional version: v2024.6.6
OS: Linux Mint 21.3
```
java --version                                                             ─╯
openjdk 11.0.23 2024-04-16
OpenJDK Runtime Environment (build 11.0.23+9-post-Ubuntu-1ubuntu122.04.1)
OpenJDK 64-Bit Server VM (build 11.0.23+9-post-Ubuntu-1ubuntu122.04.1, mixed mode, sharing)
```

**Comment by ddwightx** [comment]
Hi @rhamaa. Do you have anything set in the `HTTP Message` field or is it left blank?

**Comment by ddwightx** [comment]
@rhamaa Looks like there is a bug when this field is left blank. That should be allowed so that will be fixed. As a workaround, instead of leaving it blank, put `{{m:httprequestmessage}}`.

**Comment by ddwightx** [comment]
The bug is addressed in https://github.com/synfron/ReshaperForBurp/issues/72
