### ISSUE TITLE
v2.5.1 Run Script > return value from Reshaper.event.getMessageValue not change

### ISSUE THREAD

**Issue by sondk** [synfron/ReshaperForBurp#74]
I tried to get value of body message from HTTP request in Repeater using `Reshaper.event.getMessageValue("HttpRequestBody", "")`.
However, this function always return value from first call and keep this value persistent when i change body data in `Repeater`.
![{043AA765-DE33-4E12-BBCB-D50710FC4B6B}](https://github.com/user-attachments/assets/37943bc8-36fe-4f01-8815-8d366fdae00c)
![image](https://github.com/user-attachments/assets/e1b738c6-0b4c-4c3a-8ec6-067035d8cddf)

Reshaper v2.5.1
Burp Suite Professional v2024.8
Windows 11
openjdk version "21.0.4"

**Comment by ddwightx** [comment]
Hi @sondk. Please export your rules as JSON or Yaml and attach them here. Be sure to first remove any private or proprietary data.

**Comment by sondk** [comment]
Hi @ddwightx , here is exported rules as JSON.
[ReshaperBackup.json](https://github.com/user-attachments/files/16956948/ReshaperBackup.json)
btw, when using v2.4.0 its work. I downloaded v2.5.1 from `releases`.

**Comment by ddwightx** [comment]
@sondk Thanks for the excellent report. This has been fixed in v2.5.2.
