### ISSUE TITLE
Set Color from JavaScript

### ISSUE THREAD

**Issue by RCrozier** [synfron/ReshaperForBurp#8]
Great extension, I am using this heavily through my workflow but I have one small limitation.

I would love it if the functionality to Highlight an item can be exposed through the JavaScript Reshaper object.

Perhaps even exposing the ability to add a Comment in Proxy functionality would be another helpful feature.

**Comment by ddwightx** [comment]
Thanks for the feedback @RCrozier. I'm glad the extension has been helpful. These sound like useful additions. I'll look into getting them added.

**Comment by ddwightx** [comment]
This is addressed in Release #9 . This is not yet available in the BAppStore.

**Comment by RCrozier** [comment]
Thank you very much for putting in the work to add these features, and thank you again for creating the extension in the first place.

I feel this extension is very underrated and deserves more attention. I will be giving an internal talk to my colleagues early next year about my workflow and how it relies heavily on this extension.
